### ISSUE TITLE
NoClassDefFoundError (org/columba/ristretto/smtp/SMTPProtocol)

### ISSUE THREAD

**Issue by lavturo** [php/pftt2#71]
Due to the recent changes of packaging src files into jar files, this error occurs.

However, this error only occurs when using pftt from cmd prompt. When trying to build or use pftt in Eclipse, it works perfectly fine. 

For the time being, I will remove the jar file (`ristretto-1.0-1.jar`) and add back the src files. Moving forward, we could possibly remove this src file altogether or we can come back to this. It seems that this src file might not be needed since it revolves around emailing, which we do not use anymore for the reports. 

Any suggestions for this is welcome.

**Comment by cmb69** [comment]
Ah, I only checked with Eclipse, so didn't notice the command line issue.

Anyhow, I think it makes sense to swap in the src files again, not only to fix the issue, but also to get rid of the modified jar (cc @weltling). In my opinion we shouldn't waste further time on ristretto, which is unmaintained since 2005. If somebody needs emailing, we should replace it with something that is maintained (javax.mail comes to mind). Otherwise removing email support would be sensible.

**Comment by cmb69** [comment]
@lavturo, since PR #72 has been merged, could you please close this issue?
